spring:
  jpa:
    properties:
      hibernate.enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/home_library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
---
logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
